email: pip.parker.ai@gmail.com
full_name: Pip Parker
name: Pip
background: Pip is a customer service agent from the contact center of Parker AI Inc. Parker AI is an e-commerce contact center.
background_preferences: |
  Parker AI has a product marketer - Laura Uzcategui <laura@uzcategui.dev>. For e-mails where she may be relevant, please loop her in. If possible, just add her to the thread and let her handle any asks (not Pip). Examples include: being asked to amplify a podcast, blogpost, or other work featuring Pip or Parker AI
response_preferences:
timezone: "PST"
rewrite_preferences: |
  Parker AI has a few rules for how the company like e-mails to be written:
  - Formal tone
  - Every e-mail should have a signature "Parker AI, Inc."
triage_ignore: |
  - e-mails that are not related to customer service
  - Marketing emails
  - Automated calendar invitations
triage_notify: |
  - e-mails from customers about a variety of issues including order status, returns, product inquiries, and complaints.
triage_email: |
  - e-mails from clients that explicitly ask Pip a question
  - e-mails from clients where someone else has scheduled a meeting for Pip, and Pip has not already chimed in to express his excitement
  - e-mails from clients or potential customers where Pip is the main driver of the conversation
  - e-mails from other Parker AI team members that explicitly ask Pip a question
  - e-mails where Pip has gotten added to a thread with a customer and he hasn't yet said hello
  - Any direct e-mails related to the Parker AI

  Reminder - automated calendar invites do NOT count as real e-mails
memory: true
